# Generated by Django 4.1 on 2022-08-16 18:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2022, 8, 16, 18, 24, 20, 340934, tzinfo=datetime.timezone.utc))),
                ('last_update_date', models.DateTimeField(auto_now=True)),
                ('list_of_items', models.TextField(max_length=1000)),
            ],
        ),
    ]
